# Use Rocky Linux as the base image
FROM rockylinux:9.1

# Install Java and Maven
RUN dnf -y update && \
    dnf -y install java-1.8.0-openjdk-devel maven && \
    dnf clean all

# Set the working directory for the app
WORKDIR /app

# Copy the project files to the container
COPY . .

# Build the project with Maven
RUN mvn clean package


# Set the default command to run the app
CMD ["java", "-jar", "target/demoapp-1.0-SNAPSHOT.jar"]
